import { useMutation } from '@tanstack/react-query'
import axios from 'axios'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const url = 'https://cbfa-36-228-77-166.jp.ngrok.io/data'

export default function Home() {
  const [displayStatus, setdisplayStatus] = useState('未傳送')
  const onChainFn = async (n: number) => {
    const transferData = {
      id: 'id',
      verifyBy: '立恩威驗證股份有限公司',
      onChainTime: 'Thu Oct 27 2022 18:14:01 GMT+0800 (Taipei Standard Time)',
      verifyTime: ' Thu Oct 27 2022 18:14:01 GMT+0800 (Taipei Standard Time)',
    }
    console.log(
      '🚀 -> file: PutDataOnChainPage.tsx -> line 55 -> onChainFn -> transferData',
      transferData
    )
    if (n === 1) {
      const res = await fetch(url, {
        method: 'POST',
        mode: 'no-cors',
        body: JSON.stringify(transferData),
        headers: new Headers({
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        }),
      })
      console.log('🚀 -> file: PutDataOnChainPage.tsx -> line 68 -> onChainFn -> res', res)
      const data = await res.json()
      console.log('🚀 -> file: PutDataOnChainPage.tsx -> line 65 -> onChainFn -> data', data)
      return data
    }
    if (n === 2) {
      // const { data } = await axios.post(BLOCKCHAIN_URL, {
      axios.defaults.headers.post['Content-Type'] = 'application/json;charset=utf-8'
      axios.defaults.headers.post['Access-Control-Allow-Origin'] = '*'
      const { data } = await axios.post('https://cbfa-36-228-77-166.jp.ngrok.io/data', transferData)
      return data
    }
  }
  const onChainConfig = {
    onMutate: () => {
      setdisplayStatus('傳送中')
    },
    onSuccess: () => {
      setdisplayStatus('傳送成功')
    },
    onError: () => {
      setdisplayStatus('傳送失敗')
    },
  }
  const { mutate: putDataOnChain } = useMutation((n: number) => onChainFn(n), onChainConfig)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>傳送狀態：{displayStatus}</div>
      <div>
        <button onClick={() => putDataOnChain(1)}>傳送1</button>
        <button onClick={() => putDataOnChain(2)}>傳送2</button>
      </div>
    </div>
  )
}
